import type { Bi, PatternId } from './schema'

export const PATTERNS: Record<PatternId, Bi> = {
  'graph-bfs': { pt: 'BFS em grafo', en: 'Graph BFS' },
  'grid-bfs': { pt: 'BFS em grid', en: 'Grid BFS' },
  'multi-source-bfs': { pt: 'BFS multi-origem', en: 'Multi-source BFS' },
  'dfs-flood-fill': { pt: 'DFS / flood fill', en: 'DFS / flood fill' },
  'union-find': { pt: 'Union-Find', en: 'Union-Find' },
  'topo-sort': { pt: 'Ordenação topológica (Kahn)', en: 'Topological sort (Kahn)' },
  'topo-sort-heap': { pt: 'Topo sort + heap (desempate)', en: 'Topo sort + heap (tie-break)' },
  dijkstra: { pt: 'Dijkstra', en: 'Dijkstra' },
  'bellman-ford': { pt: 'Bellman-Ford (k rodadas)', en: 'Bellman-Ford (k rounds)' },
  'sweep-line': { pt: 'Sweep line (eventos ordenados)', en: 'Sweep line (sorted events)' },
  'sort-intervals': { pt: 'Ordenar intervalos + varrer', en: 'Sort intervals + scan' },
  heap: { pt: 'Heap / priority queue', en: 'Heap / priority queue' },
  'monotonic-deque': { pt: 'Deque monotônica', en: 'Monotonic deque' },
  'binary-search': { pt: 'Busca binária', en: 'Binary search' },
  'two-pointers': { pt: 'Dois ponteiros', en: 'Two pointers' },
  'hash-map-count': { pt: 'Contagem com hash map', en: 'Hash map counting' },
  'bucket-sort': { pt: 'Bucket sort por frequência', en: 'Bucket sort by frequency' },
  quickselect: { pt: 'Quickselect', en: 'Quickselect' },
  trie: { pt: 'Trie', en: 'Trie' },
  'trie-dfs': { pt: 'Trie + DFS podada', en: 'Trie + pruned DFS' },
  hierholzer: { pt: 'Hierholzer (caminho euleriano)', en: 'Hierholzer (Eulerian path)' },
  'hash-map-linked-list': { pt: 'Hash map + lista duplamente ligada', en: 'Hash map + doubly linked list' },
  'queue-window': { pt: 'Fila / janela deslizante', en: 'Queue / sliding window' },
  'tree-recursion': { pt: 'Recursão em árvore (dividir)', en: 'Tree recursion (divide)' },
  'linked-list-pointers': { pt: 'Reconectar ponteiros', en: 'Pointer rewiring' },
  greedy: { pt: 'Guloso', en: 'Greedy' },
  'simulation-heap': { pt: 'Simulação com dois heaps', en: 'Simulation with two heaps' },
  'candidate-enumeration': { pt: 'Enumerar poucos candidatos', en: 'Enumerate few candidates' },
  dp: { pt: 'Programação dinâmica', en: 'Dynamic programming' },
  backtracking: { pt: 'Backtracking', en: 'Backtracking' },
  'prefix-sum': { pt: 'Soma de prefixos', en: 'Prefix sum' },
}
